apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-delivery-deploy
spec:
  selector:
    matchLabels:
      tier: back-delivery
  replicas: 1
  template:
    metadata:
      labels:
        tier: back-delivery
    spec:
      containers:
        - name: back-delivery
          image: 916553408917.dkr.ecr.ap-northeast-2.amazonaws.com/back-delivery:21
          ports:
            - containerPort: 4001
              protocol: TCP
          volumeMounts:
            - name: ebs-volume
              mountPath: /data
          resources:
            requests:
              cpu: 200m
              memory: 200M
      volumes:
        - name: ebs
          persistentVolumeClaim:
            claimName: ebs-pvc
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: back
                    operator: In
                    values:
                      - user
                      - admin
              topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: back
                    operator: In
                    values:
                      - delivery
              topologyKey: "kubernetes.io/hostname"
