apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-delivery-deploy
spec:
  selector:
    matchLabels:
      tier: back-delivery
  replicas: 1
  template:
    metadata:
      labels:
        tier: back-delivery
    spec:
      containers:
        - name: back-delivery
          image: 916553408917.dkr.ecr.ap-northeast-2.amazonaws.com/back-delivery:21
          ports:
            - containerPort: 4001
              protocol: TCP
